{{- range $appName, $appValues := .Values.apps }}
{{- if $appValues.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appmesh.serviceAccountName" ( dict "appName" $appName  "values" $appValues "context" $  ) }}
  namespace: {{ template "appmesh.namespace" $.Release.Namespace }}
  labels: 
    {{- include "appmesh.labels" $ | nindent 4 }}
{{- if $appValues.serviceAccount.automountServiceAccountToken }}    
automountServiceAccountToken: {{ $appValues.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
{{- end }}