{{- range $appName, $appValues := .Values.apps }}
---
apiVersion: appmesh.k8s.aws/v1beta2
kind: VirtualNode
metadata:
  name: {{ template "appmesh.name.resourceName" ( dict "appName" $appName "context" $ ) }}-vn
  namespace: {{ template "appmesh.namespace" $.Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{- include "appmesh.selectorLabels" $ | nindent 6 }} 
      {{- include "appmesh.appLabels" $appName | nindent 6 }}
  listeners: {{ include "appmesh.virtualnode.listeners" ( dict "values" $appValues "context" $ ) | nindent 4 }}
  {{- if $appValues.appmesh }}
  {{- if  $appValues.appmesh.backends }}
  backends: {{- include "appmesh.virtualnode.backends" $appValues.appmesh.backends | nindent 4 }}
  {{- end }}
  {{- end }}
  serviceDiscovery:
    dns:
      hostname: {{ include "appmesh.name.serviceFQName" (dict "appName" $appName "context" $ ) }}
  logging:
    accessLog:
      file:
        path: /dev/stdout 
{{- end -}}        